language: node_js
node_js:
  - "0.10"
install:
  #- npm install --save-dev jest
  - npm install --save-dev mocha-lcov-reporter coveralls
script:
  ./node_modules/.bin/mocha \
  --require blanket \
  --reporter mocha-lcov-reporter \
  tests/*test.js \
  | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - coveralls
