language: node_js
node_js:
  - "0.10"
install:
  - npm install --save-dev jest
  - npm install coveralls --save-dev
  - npm install --save-dev mocha-lcov-reporter coveralls
script:
  - npm run test
after_success:
  - coveralls
