language: node_js
node_js:
  - "stable"
install:
  - npm install
  #- npm install --save-dev blanket glob
  #- npm install coveralls --save-dev
  - npm install nyc --save-dev
script:
  - npm test
#after_success:
#  - npm run coverage
